[package]
name = "osrs-world"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
osrs-core = { path = "../osrs-core" }
osrs-cache = { path = "../osrs-cache" }
osrs-scene = { path = "../osrs-scene" }
osrs-render = { path = "../osrs-render" }

[lints]
workspace = true
