//! Export real cache terrain + floor definitions as input for the pinned-client terrain oracle.
//!
//! usage: export_terrain_oracle_input <cache-dir> <output> <scene-base-x> <scene-base-y> <region-x,region-y>...
//!
//! `scene-base-*` is the world tile coordinate of scene tile (0, 0); it must be a multiple of 8.
//! Regions that fall entirely outside the 104x104 scene are skipped. Regions whose land file is
//! missing from the cache are exported as `empty` records.

use osrs_cache::profile::TargetProfile;
use osrs_cache::transport::CacheRepository;
use osrs_core::coords::RegionCoord;
use std::fmt::Write as _;
use std::{env, fs};

const PROFILE_YAML: &str =
    include_str!("../../../profiles/osrs-live-241-2026-09-30-openrs2-2727.yaml");
const CONFIG_INDEX: u8 = 2;
const UNDERLAY_GROUP: u32 = 1;
const OVERLAY_GROUP: u32 = 4;
const SCENE_TILES: i32 = 104;

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        let _ = write!(out, "{byte:02x}");
    }
    out
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = env::args().collect();
    if args.len() < 6 {
        return Err(
            "usage: export_terrain_oracle_input <cache-dir> <output> <base-x> <base-y> <rx,ry>..."
                .into(),
        );
    }
    let profile = TargetProfile::from_yaml_str(PROFILE_YAML)?;
    let cache = CacheRepository::open(&args[1], &profile)?;
    let base_x: i32 = args[3].parse()?;
    let base_y: i32 = args[4].parse()?;

    let mut out = String::new();
    out.push_str("# generated by export_terrain_oracle_input\n");
    out.push_str("brightness 0.8\n");
    let _ = writeln!(out, "noise {base_x} {base_y}");

    for (group, tag) in [(UNDERLAY_GROUP, "underlay"), (OVERLAY_GROUP, "overlay")] {
        let metadata = cache.group_metadata(CONFIG_INDEX, group)?;
        for file_id in metadata.file_ids {
            let file = cache.read_file(CONFIG_INDEX, group, file_id, None)?;
            let _ = writeln!(out, "{tag} {file_id} {}", hex(&file.bytes));
        }
    }

    for spec in &args[5..] {
        let (rx, ry) = spec.split_once(',').ok_or("region must be x,y")?;
        let region = RegionCoord::new(rx.parse()?, ry.parse()?);
        let scene_x = region.x * 64 - base_x;
        let scene_y = region.y * 64 - base_y;
        if scene_x + 64 <= 0
            || scene_y + 64 <= 0
            || scene_x >= SCENE_TILES
            || scene_y >= SCENE_TILES
        {
            eprintln!("region {spec} lies outside the scene; skipped");
            continue;
        }
        match cache.read_map_square(region) {
            Ok(square) => {
                let _ = writeln!(
                    out,
                    "land {scene_x} {scene_y} {}",
                    hex(&square.terrain.bytes)
                );
                eprintln!(
                    "region {spec}: {} terrain bytes",
                    square.terrain.bytes.len()
                );
            }
            Err(error) => {
                eprintln!("region {spec}: no land data ({error:?}); exporting empty");
                let _ = writeln!(out, "empty {scene_x} {scene_y}");
            }
        }
    }

    fs::write(&args[2], out)?;
    Ok(())
}
