from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


path = Path("crates/osrs-cache/src/transport.rs")
text = path.read_text()

text = replace_once(
    text,
    """        let encoded = self.read_encoded_group_limited(index_id, group_id, max_encoded_bytes)?;\n        validate_encoded_container(&encoded, max_encoded_bytes, max_decoded_bytes)?;\n        let mut buffer = Buffer::<Encoded>::from(encoded);\n        if let Some(keys) = xtea {\n            buffer = buffer.with_xtea_keys(keys);\n        }\n        let decoded = buffer.decode()?.finalize();\n""",
    """        let encoded = self.read_encoded_group_limited(index_id, group_id, max_encoded_bytes)?;\n        let prepared = prepare_encoded_container_for_decode(\n            encoded,\n            xtea,\n            max_encoded_bytes,\n            max_decoded_bytes,\n        )?;\n        let decoded = Buffer::<Encoded>::from(prepared).decode()?.finalize();\n""",
    "read_decoded_group",
)

marker = "fn validate_encoded_container(\n"
helper = """fn prepare_encoded_container_for_decode(\n    mut encoded: Vec<u8>,\n    xtea: Option<[u32; 4]>,\n    max_encoded_bytes: usize,\n    max_decoded_bytes: usize,\n) -> TransportResult<Vec<u8>> {\n    validate_encoded_container_envelope(&encoded, max_encoded_bytes)?;\n    if let Some(keys) = xtea {\n        runefs::xtea::decipher(&mut encoded[5..], &keys);\n    }\n    validate_encoded_container(&encoded, max_encoded_bytes, max_decoded_bytes)?;\n    Ok(encoded)\n}\n\nfn validate_encoded_container_envelope(\n    encoded: &[u8],\n    max_encoded_bytes: usize,\n) -> TransportResult<(u8, usize, usize)> {\n    if encoded.len() > max_encoded_bytes {\n        return Err(TransportError::LimitExceeded {\n            field: \"encoded group bytes\",\n            requested: encoded.len(),\n            limit: max_encoded_bytes,\n        });\n    }\n    if encoded.len() < 5 {\n        return Err(TransportError::MalformedContainer(\n            \"container is shorter than compression byte plus length\".to_owned(),\n        ));\n    }\n    let compression = encoded[0];\n    if compression > 2 {\n        return Err(TransportError::MalformedContainer(format!(\n            \"unsupported OSRS compression id {compression}\"\n        )));\n    }\n    let compressed_len =\n        u32::from_be_bytes([encoded[1], encoded[2], encoded[3], encoded[4]]) as usize;\n    if compressed_len > max_encoded_bytes {\n        return Err(TransportError::LimitExceeded {\n            field: \"compressed payload bytes\",\n            requested: compressed_len,\n            limit: max_encoded_bytes,\n        });\n    }\n    let header_len = if compression == 0 { 5usize } else { 9usize };\n    if encoded.len() < header_len {\n        return Err(TransportError::MalformedContainer(\n            \"compressed container is missing decompressed length\".to_owned(),\n        ));\n    }\n    let payload_end = header_len.checked_add(compressed_len).ok_or_else(|| {\n        TransportError::MalformedContainer(\"payload end overflowed usize\".to_owned())\n    })?;\n    if payload_end > encoded.len() {\n        return Err(TransportError::MalformedContainer(format!(\n            \"declared compressed payload ends at {payload_end}, container length is {}\",\n            encoded.len()\n        )));\n    }\n    let trailing = encoded.len() - payload_end;\n    if trailing != 0 && trailing != 2 {\n        return Err(TransportError::MalformedContainer(format!(\n            \"container has {trailing} trailing bytes; expected zero or two-byte version\"\n        )));\n    }\n    Ok((compression, compressed_len, header_len))\n}\n\n"""
text = replace_once(text, marker, helper + marker, "insert validation helpers")

old_validator = """fn validate_encoded_container(\n    encoded: &[u8],\n    max_encoded_bytes: usize,\n    max_decoded_bytes: usize,\n) -> TransportResult<()> {\n    if encoded.len() > max_encoded_bytes {\n        return Err(TransportError::LimitExceeded {\n            field: \"encoded group bytes\",\n            requested: encoded.len(),\n            limit: max_encoded_bytes,\n        });\n    }\n    if encoded.len() < 5 {\n        return Err(TransportError::MalformedContainer(\n            \"container is shorter than compression byte plus length\".to_owned(),\n        ));\n    }\n    let compression = encoded[0];\n    if compression > 2 {\n        return Err(TransportError::MalformedContainer(format!(\n            \"unsupported OSRS compression id {compression}\"\n        )));\n    }\n    let compressed_len =\n        u32::from_be_bytes([encoded[1], encoded[2], encoded[3], encoded[4]]) as usize;\n    if compressed_len > max_encoded_bytes {\n        return Err(TransportError::LimitExceeded {\n            field: \"compressed payload bytes\",\n            requested: compressed_len,\n            limit: max_encoded_bytes,\n        });\n    }\n\n    let (header_len, decoded_len) = if compression == 0 {\n        (5usize, compressed_len)\n    } else {\n        if encoded.len() < 9 {\n            return Err(TransportError::MalformedContainer(\n                \"compressed container is missing decompressed length\".to_owned(),\n            ));\n        }\n        let decoded_len =\n            u32::from_be_bytes([encoded[5], encoded[6], encoded[7], encoded[8]]) as usize;\n        (9usize, decoded_len)\n    };\n    if decoded_len > max_decoded_bytes {\n        return Err(TransportError::LimitExceeded {\n            field: \"declared decoded group bytes\",\n            requested: decoded_len,\n            limit: max_decoded_bytes,\n        });\n    }\n    let payload_end = header_len.checked_add(compressed_len).ok_or_else(|| {\n        TransportError::MalformedContainer(\"payload end overflowed usize\".to_owned())\n    })?;\n    if payload_end > encoded.len() {\n        return Err(TransportError::MalformedContainer(format!(\n            \"declared compressed payload ends at {payload_end}, container length is {}\",\n            encoded.len()\n        )));\n    }\n    let trailing = encoded.len() - payload_end;\n    if trailing != 0 && trailing != 2 {\n        return Err(TransportError::MalformedContainer(format!(\n            \"container has {trailing} trailing bytes; expected zero or two-byte version\"\n        )));\n    }\n    Ok(())\n}\n"""
new_validator = """fn validate_encoded_container(\n    encoded: &[u8],\n    max_encoded_bytes: usize,\n    max_decoded_bytes: usize,\n) -> TransportResult<()> {\n    let (compression, compressed_len, _) =\n        validate_encoded_container_envelope(encoded, max_encoded_bytes)?;\n    let decoded_len = if compression == 0 {\n        compressed_len\n    } else {\n        u32::from_be_bytes([encoded[5], encoded[6], encoded[7], encoded[8]]) as usize\n    };\n    if decoded_len > max_decoded_bytes {\n        return Err(TransportError::LimitExceeded {\n            field: \"declared decoded group bytes\",\n            requested: decoded_len,\n            limit: max_decoded_bytes,\n        });\n    }\n    Ok(())\n}\n"""
text = replace_once(text, old_validator, new_validator, "replace full validator")

test_marker = """    #[test]\n    fn container_validation_rejects_unbounded_declared_output_before_decode() {\n"""
test = """    #[test]\n    fn xtea_container_is_deciphered_before_declared_output_validation() -> TransportResult<()> {\n        let keys = [0x1020_3040, 0x5060_7080, 0x90a0_b0c0, 0xd0e0_f000];\n        let mut encoded = vec![2, 0, 0, 0, 8, 0, 0, 0, 64];\n        encoded.extend_from_slice(&[1, 2, 3, 4, 5, 6, 7, 8]);\n        runefs::xtea::encipher(&mut encoded[5..], &keys);\n\n        let prepared = prepare_encoded_container_for_decode(encoded, Some(keys), 1024, 64)?;\n        assert_eq!(&prepared[5..9], &64u32.to_be_bytes());\n        validate_encoded_container(&prepared, 1024, 64)?;\n        Ok(())\n    }\n\n"""
text = replace_once(text, test_marker, test + test_marker, "insert XTEA ordering test")

old_legacy = """        let decoded = cache.read_decoded_group(\n            MAP_INDEX,\n            loc_group,\n            Some(LEGACY_LUMBRIDGE_XTEA),\n            usize::MAX,\n            usize::MAX,\n        )?;\n"""
new_legacy = """        let decoded = cache.read_decoded_group(\n            MAP_INDEX,\n            loc_group,\n            Some(LEGACY_LUMBRIDGE_XTEA),\n            DEFAULT_MAX_ENCODED_GROUP_BYTES,\n            DEFAULT_MAX_DECODED_GROUP_BYTES,\n        )?;\n"""
text = replace_once(text, old_legacy, new_legacy, "bound legacy XTEA regression")

path.write_text(text)
